project:
  type: website
  output-dir: docs # compiles website into docs directory?

website:
  title: "Portfolio"
  site-url: "https://MaryKatz.github.io/Portfolio/"
  repo-url: "https://github.com/MaryKatz/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: NewTab.qmd
        text: New Tab
      - href: NewSubTab.qmd
        text: New Sub Tab
        

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



